env: "local" # local, dev, prod
#db_url: "mike:mike@tcp(127.0.0.1:3306)/exchange_rates"
db:
  host: "127.0.0.1"
  port: "3306"
  name: "exchange_rates"
  user: "mike"
  pwd: "mike"
http_server:
  addr: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s